const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"新闻类型名称管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"书籍类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShujigoumai"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"捐赠书籍管理",
                        "menuJump":"列表",
                        "tableName":"juanzengshuji"
                    }
                ],
                "menu":"捐赠书籍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"书籍购买管理",
                        "menuJump":"列表",
                        "tableName":"shujigoumai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"书籍购买评价管理",
                        "menuJump":"列表",
                        "tableName":"shujigoumaiCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"书籍购买订单管理",
                        "menuJump":"列表",
                        "tableName":"shujigoumaiOrder"
                    }
                ],
                "menu":"书籍购买管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"书籍信息管理",
                        "menuJump":"列表",
                        "tableName":"shujixinxi"
                    }
                ],
                "menu":"书籍信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"书籍借阅记录管理",
			            "menuJump":"列表",
			            "tableName":"shujijieyue"
			        }
			    ],
			    "menu":"书籍借阅记录管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"预约书籍管理",
                        "menuJump":"列表",
                        "tableName":"yuyueshuji"
                    }
                ],
                "menu":"预约书籍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"捐赠书籍管理",
	                    "menuJump":"列表",
	                    "tableName":"juanzengshuji"
	                }
	            ],
	            "menu":"捐赠书籍管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"书籍购买管理",
	                    "menuJump":"列表",
	                    "tableName":"shujigoumai"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"书籍购买评价管理",
	                    "menuJump":"列表",
	                    "tableName":"shujigoumaiCommentback"
	                }
	                ,
	                {
	                    "buttons":[
	                        "订单",
	                        "查看"
	                    ],
	                    "menu":"书籍购买订单管理",
	                    "menuJump":"列表",
	                    "tableName":"shujigoumaiOrder"
	                }
	            ],
	            "menu":"书籍购买管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "还书"
	                    ],
	                    "menu":"书籍借阅记录管理",
	                    "menuJump":"列表",
	                    "tableName":"shujijieyue"
	                }
	            ],
	            "menu":"书籍借阅记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"书籍信息管理",
	                    "menuJump":"列表",
	                    "tableName":"shujixinxi"
	                }
	            ],
	            "menu":"书籍信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"预约书籍管理",
	                    "menuJump":"列表",
	                    "tableName":"yuyueshuji"
	                }
	            ],
	            "menu":"预约书籍管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
